remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark

title: "testuser的空间"

logo: "/assets/img/profile/!!.png"

footer_content: "你说你不想在这里！"

last_edit_timestamp: false

gh_edit_link: false
