remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
title: owo
author: testuser
navbar-links:
  About Me: "铸币"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdownguide.org"
